use serde::{Deserialize, Serialize};

use crate::types::NodeId;

use super::entry::IndexEntry;

/// All top-level declarations (types, errors, function signatures) visible
/// from a single folder node in the PSSD graph.
///
/// Generated by [`crate::index::generate_folder_index_for_node`].
/// `Do` node bodies are excluded — only their signatures appear here.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FolderIndex {
    /// Name of the folder node (from `node.metadata.name`), or empty string for unnamed roots.
    pub folder_name: String,
    /// The graph node that roots this folder.
    pub folder_node_id: NodeId,
    /// All named, indexable declarations in this folder's subtree.
    pub entries: Vec<IndexEntry>,
}
