use crate::types::{EmitConfig, EmitOutput, EmittedFile, FileOwnership, TestFramework};

// ── Public entry point ─────────────────────────────────────────────────────────

/// Emit TypeScript project configuration files into the output root.
///
/// Generates `tsconfig.json`, `package.json`, and `ail-runtime.ts` (always).
/// When `config.test_framework` is [`TestFramework::Jest`], also generates
/// `jest.config.ts` because Jest + ESM + TypeScript requires an explicit preset.
///
/// All files are [`FileOwnership::Generated`] (overwritten on every build).
pub fn emit_ts_project_files(config: &EmitConfig) -> EmitOutput {
    let mut files: Vec<EmittedFile> = Vec::new();

    files.push(emit_tsconfig());
    files.push(emit_package_json(config));
    files.push(emit_ail_runtime());

    if config.test_framework == TestFramework::Jest {
        files.push(emit_jest_config());
    }

    EmitOutput { files }
}

// ── tsconfig.json ──────────────────────────────────────────────────────────────

fn emit_tsconfig() -> EmittedFile {
    // Spec: AIL-TypeScript-Emitter-v2.0.md §project-files
    // `include` covers all generated TypeScript files so `tsc --noEmit` validates
    // the full output in one pass.  `ail-runtime.ts` and `tests/**/*.ts` must be
    // listed explicitly: the runtime is not reachable transitively from
    // `types/`/`errors/`, and `tests/` is not reachable from any `include` entry.
    let content = r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "outDir": "./dist",
    "rootDir": "./",
    "declaration": true,
    "sourceMap": true
  },
  "include": [
    "types/**/*.ts",
    "errors/**/*.ts",
    "fn/**/*.ts",
    "./ail-runtime.ts",
    "tests/**/*.ts"
  ]
}
"#;
    EmittedFile {
        path: "tsconfig.json".to_owned(),
        content: content.to_owned(),
        ownership: FileOwnership::Generated,
    }
}

// ── package.json ───────────────────────────────────────────────────────────────

fn emit_package_json(config: &EmitConfig) -> EmittedFile {
    let content = match config.test_framework {
        TestFramework::Vitest => {
            r#"{
  "name": "ail-generated",
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "test": "vitest run",
    "typecheck": "tsc --noEmit"
  },
  "devDependencies": {
    "vitest": "^2.0.0",
    "typescript": "^5.0.0"
  }
}
"#
        }
        TestFramework::Jest => {
            r#"{
  "name": "ail-generated",
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "test": "node --experimental-vm-modules node_modules/.bin/jest",
    "typecheck": "tsc --noEmit"
  },
  "devDependencies": {
    "@jest/globals": "^29.0.0",
    "ts-jest": "^29.0.0",
    "typescript": "^5.0.0"
  }
}
"#
        }
    };
    EmittedFile {
        path: "package.json".to_owned(),
        content: content.to_owned(),
        ownership: FileOwnership::Generated,
    }
}

// ── jest.config.ts (Jest only) ─────────────────────────────────────────────────

fn emit_jest_config() -> EmittedFile {
    // Jest + ESM + TypeScript requires explicit preset/transform configuration.
    let content = r#"import type { Config } from '@jest/globals';
export default {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
} satisfies Config;
"#;
    EmittedFile {
        path: "jest.config.ts".to_owned(),
        content: content.to_owned(),
        ownership: FileOwnership::Generated,
    }
}

// ── ail-runtime.ts ─────────────────────────────────────────────────────────────

fn emit_ail_runtime() -> EmittedFile {
    // Inline runtime (v2.0): avoids an external npm package dependency.
    // v3.0 plan: publish as `ail-runtime-ts` on npm.
    let content = r#"/*
 * AIL TypeScript runtime helpers.
 * Copyright (c) 2026 PhanNhuong123
 * SPDX-License-Identifier: MIT
 */
// Generated by ail build, do not edit.

export function pre(condition: boolean, message: string): void {
  if (!condition) throw new Error(`Precondition failed: ${message}`);
}

export function post(condition: boolean, message: string): void {
  if (!condition) throw new Error(`Postcondition failed: ${message}`);
}

export function keep(condition: boolean, message: string): void {
  if (!condition) throw new Error(`Invariant failed: ${message}`);
}
"#;
    EmittedFile {
        path: "ail-runtime.ts".to_owned(),
        content: content.to_owned(),
        ownership: FileOwnership::Generated,
    }
}

// ── Tests ──────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn vitest_config() -> EmitConfig {
        EmitConfig::default() // Vitest is the default
    }

    fn jest_config() -> EmitConfig {
        EmitConfig {
            test_framework: TestFramework::Jest,
            ..Default::default()
        }
    }

    #[test]
    fn emit_returns_three_files_vitest() {
        let output = emit_ts_project_files(&vitest_config());
        assert_eq!(
            output.files.len(),
            3,
            "vitest should produce exactly 3 files"
        );
        let paths: Vec<&str> = output.files.iter().map(|f| f.path.as_str()).collect();
        assert!(paths.contains(&"tsconfig.json"));
        assert!(paths.contains(&"package.json"));
        assert!(paths.contains(&"ail-runtime.ts"));
    }

    #[test]
    fn emit_returns_four_files_jest() {
        let output = emit_ts_project_files(&jest_config());
        assert_eq!(output.files.len(), 4, "jest should produce exactly 4 files");
        let paths: Vec<&str> = output.files.iter().map(|f| f.path.as_str()).collect();
        assert!(paths.contains(&"jest.config.ts"));
    }

    #[test]
    fn tsconfig_includes_all_required_paths() {
        let output = emit_ts_project_files(&vitest_config());
        let tsconfig = output
            .files
            .iter()
            .find(|f| f.path == "tsconfig.json")
            .unwrap();
        assert!(
            tsconfig.content.contains("types/**/*.ts"),
            "missing types/**/*.ts"
        );
        assert!(
            tsconfig.content.contains("errors/**/*.ts"),
            "missing errors/**/*.ts"
        );
        assert!(
            tsconfig.content.contains("fn/**/*.ts"),
            "missing fn/**/*.ts"
        );
        assert!(
            tsconfig.content.contains("./ail-runtime.ts"),
            "missing ./ail-runtime.ts"
        );
        assert!(
            tsconfig.content.contains("tests/**/*.ts"),
            "missing tests/**/*.ts"
        );
    }

    #[test]
    fn tsconfig_has_strict_mode() {
        let output = emit_ts_project_files(&vitest_config());
        let tsconfig = output
            .files
            .iter()
            .find(|f| f.path == "tsconfig.json")
            .unwrap();
        assert!(
            tsconfig.content.contains("\"strict\": true"),
            "strict mode missing"
        );
    }

    #[test]
    fn package_json_vitest_default() {
        let output = emit_ts_project_files(&vitest_config());
        let pkg = output
            .files
            .iter()
            .find(|f| f.path == "package.json")
            .unwrap();
        assert!(pkg.content.contains("\"vitest\""), "vitest dep missing");
        assert!(
            pkg.content.contains("\"test\": \"vitest run\""),
            "test script missing"
        );
        assert!(
            !pkg.content.contains("jest"),
            "jest must not appear in vitest config"
        );
    }

    #[test]
    fn package_json_jest_variant() {
        let output = emit_ts_project_files(&jest_config());
        let pkg = output
            .files
            .iter()
            .find(|f| f.path == "package.json")
            .unwrap();
        assert!(
            pkg.content.contains("\"@jest/globals\""),
            "@jest/globals dep missing"
        );
        assert!(pkg.content.contains("\"ts-jest\""), "ts-jest dep missing");
        assert!(
            !pkg.content.contains("vitest"),
            "vitest must not appear in jest config"
        );
    }

    #[test]
    fn ail_runtime_contains_all_three_functions() {
        let output = emit_ts_project_files(&vitest_config());
        let runtime = output
            .files
            .iter()
            .find(|f| f.path == "ail-runtime.ts")
            .unwrap();
        assert!(
            runtime.content.contains("export function pre("),
            "pre missing"
        );
        assert!(
            runtime.content.contains("export function post("),
            "post missing"
        );
        assert!(
            runtime.content.contains("export function keep("),
            "keep missing"
        );
    }

    #[test]
    fn ail_runtime_has_mit_notice() {
        let output = emit_ts_project_files(&vitest_config());
        let runtime = output
            .files
            .iter()
            .find(|f| f.path == "ail-runtime.ts")
            .unwrap();
        assert!(
            runtime.content.contains("SPDX-License-Identifier: MIT"),
            "MIT SPDX notice missing"
        );
        assert!(
            runtime.content.contains("Copyright (c) 2026 PhanNhuong123"),
            "MIT copyright notice missing"
        );
    }

    #[test]
    fn all_files_are_generated_ownership() {
        let output = emit_ts_project_files(&vitest_config());
        for file in &output.files {
            assert_eq!(
                file.ownership,
                FileOwnership::Generated,
                "file {} should be Generated ownership",
                file.path
            );
        }
    }
}
